version: "3.8"
services:
  twitch_bot:
   build: .
   container_name: twitch_bot
   volumes:
     - ./src:/tmp
   environment:
     - APP_ID
     - APP_SECRET
     - TWITCH_USER
   entrypoint: tail -f
